prettier

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -16,17 +16,24 @@
 #
 set -e -o pipefail
 
+if [[ -z $AWS_PROFILE ]]; then
+	echo "ERROR: refusing to deploy to the default AWS profile" >&2
+	exit 1
+fi
+
 if [[ $1 != ENABLED ]]  && [[ $1 != DISABLED ]] ; then
 	echo "Usage: $(basename $0) [ENABLED|DISABLED]" >&2
 	exit 1
 fi
 
+echo "INFO: retrieving account id" >&2
 ACCOUNT=$(aws sts get-caller-identity --query Account --output text || exit 0)
 if [[ -z $ACCOUNT ]]; then
 	echo "ERROR: failed to determine AWS account number">&2
 	exit 1
 fi
 
+echo "INFO: retrieving account alias" >&2
 ALIAS=$(aws iam  list-account-aliases  --query AccountAliases  --output text || exit 0)
 if [[ -z $ALIAS ]]; then
 	echo "ERROR: account $ACCOUNT does not have an account alias.">&2
@@ -41,6 +48,7 @@ if [[ $CONTINUE != yes ]]; then
 	exit 1
 fi
 
+echo "INFO: deploying CloudFormation stack 'aws-account-destroyer'" >&2
 aws cloudformation deploy \
         --no-fail-on-empty-changeset \
         --stack-name aws-account-destroyer \
@@ -48,3 +56,5 @@ aws cloudformation deploy \
         --capabilities CAPABILITY_NAMED_IAM \
         --parameter-overrides ScheduledEvent=${1:-DISABLED}
 
+
+echo "INFO: now modify aws-nuke.yaml.template commit and push to remote codecommit://${AWS_PROFILE}@aws-account-destroyer" >&2
